// <auto-generated />
using System;
using Gestion.dinventaire.Backend.DAL.Enteties;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion.dinventaire.Backend.DAL.Migrations
{
    [DbContext(typeof(APIContext))]
    [Migration("20220901131622_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Gestion.dinventaire.Backend.Models.ChaiseBurautique", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("dateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reference")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id")
                        .HasName("PK_chaise");

                    b.ToTable("T_chaise", (string)null);
                });

            modelBuilder.Entity("Gestion.dinventaire.Backend.Models.Clavier", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("dateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reference")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id")
                        .HasName("PK_clavier");

                    b.ToTable("T_Clavier", (string)null);
                });

            modelBuilder.Entity("Gestion.dinventaire.Backend.Models.Computer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reference")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id")
                        .HasName("PK_computer");

                    b.ToTable("T_Computer", (string)null);
                });

            modelBuilder.Entity("Gestion.dinventaire.Backend.Models.Employee", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<bool>("IsActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("chaisid")
                        .HasColumnType("int");

                    b.Property<int?>("clavierid")
                        .HasColumnType("int");

                    b.Property<int?>("computerid")
                        .HasColumnType("int");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("tableid")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id")
                        .HasName("PK_Employee");

                    b.HasIndex("chaisid");

                    b.HasIndex("clavierid");

                    b.HasIndex("computerid");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("tableid");

                    b.ToTable("T_Employee", (string)null);

                    b.HasCheckConstraint("checkMinLenMail", "lEN(Email)>=5");
                });

            modelBuilder.Entity("Gestion.dinventaire.Backend.Models.Table", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("dateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reference")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id")
                        .HasName("PK_Table");

                    b.ToTable("T_Table", (string)null);
                });

            modelBuilder.Entity("Gestion.dinventaire.Backend.Models.Employee", b =>
                {
                    b.HasOne("Gestion.dinventaire.Backend.Models.ChaiseBurautique", "chais")
                        .WithMany("employees")
                        .HasForeignKey("chaisid");

                    b.HasOne("Gestion.dinventaire.Backend.Models.Clavier", "clavier")
                        .WithMany("employees")
                        .HasForeignKey("clavierid");

                    b.HasOne("Gestion.dinventaire.Backend.Models.Computer", "computer")
                        .WithMany("employees")
                        .HasForeignKey("computerid");

                    b.HasOne("Gestion.dinventaire.Backend.Models.Table", "table")
                        .WithMany("employees")
                        .HasForeignKey("tableid");

                    b.Navigation("chais");

                    b.Navigation("clavier");

                    b.Navigation("computer");

                    b.Navigation("table");
                });

            modelBuilder.Entity("Gestion.dinventaire.Backend.Models.ChaiseBurautique", b =>
                {
                    b.Navigation("employees");
                });

            modelBuilder.Entity("Gestion.dinventaire.Backend.Models.Clavier", b =>
                {
                    b.Navigation("employees");
                });

            modelBuilder.Entity("Gestion.dinventaire.Backend.Models.Computer", b =>
                {
                    b.Navigation("employees");
                });

            modelBuilder.Entity("Gestion.dinventaire.Backend.Models.Table", b =>
                {
                    b.Navigation("employees");
                });
#pragma warning restore 612, 618
        }
    }
}
